/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAprobacionesRouteImport } from './routes/app.aprobaciones'
import { Route as AppFinanzasRouteImport } from './routes/app.finanzas'
import { Route as AppNuevoRouteImport } from './routes/app.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAprobacionesRoute = AppAprobacionesRouteImport.update({
  id: '/aprobaciones',
  path: '/aprobaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppNuevoRoute = AppNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/aprobaciones': typeof AppAprobacionesRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/nuevo': typeof AppNuevoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/aprobaciones': typeof AppAprobacionesRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/nuevo': typeof AppNuevoRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/aprobaciones': typeof AppAprobacionesRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/nuevo': typeof AppNuevoRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/aprobaciones'
    | '/app/finanzas'
    | '/app/nuevo'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/aprobaciones' | '/app/finanzas' | '/app/nuevo' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/aprobaciones'
    | '/app/finanzas'
    | '/app/nuevo'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprobaciones': {
      id: '/app/aprobaciones'
      path: '/aprobaciones'
      fullPath: '/app/aprobaciones'
      preLoaderRoute: typeof AppAprobacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finanzas': {
      id: '/app/finanzas'
      path: '/finanzas'
      fullPath: '/app/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nuevo': {
      id: '/app/nuevo'
      path: '/nuevo'
      fullPath: '/app/nuevo'
      preLoaderRoute: typeof AppNuevoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAprobacionesRoute: typeof AppAprobacionesRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppNuevoRoute: typeof AppNuevoRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprobacionesRoute: AppAprobacionesRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppNuevoRoute: AppNuevoRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
